made some quality of life changes, hope you find it useful
30023344/Backup-Script pull request #13
Opened 2023-04-05 08:59 UTC by GarNepNep

Honestly it took me awhile to figure out how to use jobs,

2023-04-06 00:35 UTC, 30023344 commented
i forgot i made this open to contributions, ill check this out later today

2023-04-06 00:38 UTC, 30023344 commented
this was a school project so it was never meant to be perfect, but i did spend a bit of time adding extra stuff to it.

2023-04-06 04:51 UTC, 30023344 requested changes
## summary:

### Proposed changes
- changed constants to use a different naming convention
- changed names of some variables to be more readable
- made comments and messages more readable by moving them to separate lines

### Comments
Looks good. I will apply suggestions and push to a new branch where I will test if the new changes work, and if they do, I will push to main.

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +from backupcfg import *
```suggestion
```
if for some reason backupcfg.py doesn't exist, an error will occur, and the program will stop. this is why I made it do a check for if the file exists later on in the program before importing it.

2023-04-06 04:51 UTC, 30023344 commented on backup.py
```suggestion
try:
    from backupcfg import *
except:
    backupLog.write("\n" + datetime.now().strftime('%Y-%m-%d %H:%M:%S ') + "Backup Cancelled: Importing config file failed. Check to see if jobs are defined correctly.\n")
```
this should hopefully fix issue #12 where incorrectly defining jobs cause a crash.

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +            writeToLog(pathlib.PurePath(n).name +
```suggestion
            writeToLog(pathlib.PurePath(jobPath).name +
```
'n' got changed to 'jobPath' but wasn't changed here. I like that the names were changed to be more readable, I was too lazy to do this myself.

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +            writeToLog(pathlib.PurePath(n).name +
```suggestion
            writeToLog(pathlib.PurePath(jobPath).name +
```

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +        writeToLog(pathlib.PurePath(
```suggestion
        writeToLog(pathlib.PurePath(jobPath).name + 
```

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +            n).name + " Error: '%s' could not be backed up with unknown reason." % n, True)
```suggestion
            " Error: '%s' could not be backed up with unknown reason." % n, True)
```

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +            n).name + " Error: '%s' could not be backed up with unknown reason." % n, True)
I actually don't know if this outputs what I want it to.

2023-04-06 04:51 UTC, 30023344 commented on backupcfg.py
> +# These are constants because they're not expected to change over runtime
so you used a different naming convention to differentiate the two? anyway, this is good because I can easily tell the difference now.

2023-04-06 04:51 UTC, 30023344 commented on backupcfg.py
> +backupDir = "./backup/"  # could reference this in 'directory'
random space.

2023-04-06 04:51 UTC, 30023344 commented on backup.py
> +# this bit copies files
Thank you, grammar cop.

2023-04-06 08:54 UTC, GarNepNep commented on backup.py
> +            writeToLog(pathlib.PurePath(n).name +
Sorry my dude, I got sloppy :/

2023-04-12 06:46 UTC, GarNepNep commented on backup.py
> +from backupcfg import *
Without the cfg then the script shouldn't run anyway? No real point of redundancy. I may have missed a finer detail tho.

2023-08-26 11:39 UTC, closed without merging